import csv

# define the keywords
keywords = {
        "ERP software": [
        "erp",
        "enterprise resource planning",
        "accounting",
        "financial management",
        "inventory control",
        "project management",
        "reporting",
        "analytics",
        "workflow automation",
        "multi-currency",
        "multi-language",
        "multi-company",
        "fixed assets",
        "payables",
        "receivables",
        "general ledger",
        "tax management",
        "edi",
        "sales orders",
        "purchase orders",
        "supply chain integration",
        "manufacturing integration",
        "real-time updates",
        "cloud-based",
        "customizable",
        "user-friendly",
        "scalable",
        "erp consulting",
        "erp implementation",
        "erp software vendors",
        "budgeting",
        "forecasting",
        "business process management",
        "data management",
        "mobile access",
        "intercompany transactions",
        "cash management",
        "audit trails",
        "compliance",
        "crm integration",
        "demand planning",
        "financial planning",
        "consolidation",
        "fixed budgeting",
        "financial reporting",
        "management reporting",
        "tax compliance",
        "multi-entity accounting",
        "financial analytics",
        "business intelligence",
        "general accounting"
    ],
    "Supply Chain software": [
        "supply chain",
        "warehouse management",
        "transportation management",
        "fleet management",
        "inventory management",
        "demand planning",
        "logistics",
        "supply chain compliance",
        "trade compliance",
        "purchasing",
        "procurement",
        "order management",
        "supply chain visibility",
        "distribution",
        "shipping",
        "receiving",
        "inventory control",
        "replenishment",
        "demand forecasting",
        "sourcing",
        "vendor management",
        "routing",
        "pick and pack",
        "parcel shipping",
        "freight",
        "import",
        "export",
        "cross-docking",
        "automated warehouse",
        "yard management",
        "inventory accuracy",
        "cycle counting",
        "rfid",
        "barcode scanning",
        "material handling",
        "workforce management",
        "automated data collection",
        "real-time tracking",
        "delivery optimization",
        "load optimization",
        "route optimization",
        "last-mile delivery",
        "supply chain analytics",
        "cloud-based",
        "on-premise",
        "customizable",
        "user-friendly",
        "scalable",
        "supply chain consulting",
        "supply chain implementation",
        "supply chain software vendors"
    ],
    "Procurement software": [
        "procurement",
        "source-to-pay",
        "source-to-contract",
        "procure-to-pay",
        "purchase-to-pay",
        "sourcing",
        "ap automation",
        "e-invoicing",
        "supplier management",
        "contract management",
        "supplier performance management",
        "spend analysis",
        "procurement analytics",
        "category management",
        "strategic sourcing",
        "rfp",
        "rfq",
        "rfi",
        "reverse auction",
        "catalog management",
        "inventory management",
        "order management",
        "compliance management",
        "e-sourcing",
        "e-rfx",
        "e-auction",
        "contract authoring",
        "contract compliance",
        "contract negotiation",
        "purchase requisitions",
        "purchase orders",
        "purchase approvals",
        "purchase order tracking",
        "purchase order matching",
        "supplier onboarding",
        "supplier discovery",
        "supplier collaboration",
        "supplier portal",
        "supplier qualification",
        "supplier risk management",
        "supplier diversity",
        "supplier scorecarding",
        "spend management",
        "vendor management",
        "vendor compliance",
        "vendor onboarding",
        "vendor collaboration",
        "vendor portal",
        "vendor performance management",
        "vendor risk management",
        "cloud-based",
        "on-premise",
        "customizable",
        "user-friendly",
        "scalable",
        "procurement consulting",
        "procurement implementation",
        "procurement software vendors"
    ],
    "Other": [
        "crm",
        "customer relationship management",
        "project management",
        "task management",
        "team collaboration",
        "time tracking",
        "invoice management",
        "expense management",
        "sales automation",
        "sales forecasting",
        "sales performance management",
        "sales analytics",
        "lead management",
        "opportunity management",
        "pipeline management",
        "marketing automation",
        "email marketing",
        "lead nurturing",
        "lead scoring",
        "campaign management",
        "social media marketing",
        "customer segmentation",
        "data analytics",
        "business intelligence",
        "data visualization",
        "dashboard",
        "reporting",
        "data mining",
        "predictive analytics",
        "artificial intelligence",
        "machine learning",
        "big data",
        "cloud computing",
        "saas",
        "paas",
        "iaas",
        "data integration",
        "data warehousing",
        "etl",
        "api integration",
        "system integration",
        "erp integration",
        "crm integration",
        "business process automation",
        "workflow automation",
        "document management",
        "content management",
        "knowledge management",
        "enterprise search",
        "enterprise architecture",
        "enterprise mobility",
        "mobile device management",
        "cybersecurity",
        "network security",
        "data security",
        "cloud security",
        "compliance management",
        "gdpr",
        "hipaa",
        "pci-dss",
        "itil",
        "iso 27001",
        "customizable",
        "user-friendly",
        "scalable",
    ],
}

# determine the number of keyword columns needed
max_keywords = max(len(keywords_list) for keywords_list in keywords.values())

# create the header row with the appropriate number of columns
header_row = ["#", "Category"]
header_row.extend(f"Keyword {i}" for i in range(1, max_keywords+1))

# open the CSV file for writing
with open("data/categories_updated.csv", "w", newline="", encoding="utf-8") as f:
    # create the CSV writer object
    writer = csv.writer(f, delimiter=";")
    # write the header row
    writer.writerow(header_row)
    # write the keyword data for each category
    for i, (category, keywords_list) in enumerate(keywords.items(), start=1):
        keywords_list = [keyword.lower() for keyword in keywords_list]
        row = [i, category] + keywords_list + [""] * (max_keywords - len(keywords_list))
        writer.writerow(row)
